# docker-compose.yml
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend/staticfiles:/staticfiles
    depends_on:
      - web
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web
    command: "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"

networks:
  app-tier:
    driver: bridge      